//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigoNFE.Status3_BA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico", ConfigurationName="Status3_BA.NfeStatusServicoSoap")]
    public interface NfeStatusServicoSoap {
        
        // CODEGEN: Generating message contract since the operation NfeStatusServicoNF is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico/NfeStatusServicoNF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VigoNFE.Status3_BA.NfeStatusServicoNFResponse NfeStatusServicoNF(VigoNFE.Status3_BA.NfeStatusServicoNFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico/NfeStatusServicoNF", ReplyAction="*")]
        System.Threading.Tasks.Task<VigoNFE.Status3_BA.NfeStatusServicoNFResponse> NfeStatusServicoNFAsync(VigoNFE.Status3_BA.NfeStatusServicoNFRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico")]
    public partial class nfeCabecMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versaoDadosField;
        
        private string cUFField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string versaoDados {
            get {
                return this.versaoDadosField;
            }
            set {
                this.versaoDadosField = value;
                this.RaisePropertyChanged("versaoDados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cUF {
            get {
                return this.cUFField;
            }
            set {
                this.cUFField = value;
                this.RaisePropertyChanged("cUF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NfeStatusServicoNFRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico")]
        public VigoNFE.Status3_BA.nfeCabecMsg nfeCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public NfeStatusServicoNFRequest() {
        }
        
        public NfeStatusServicoNFRequest(VigoNFE.Status3_BA.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            this.nfeCabecMsg = nfeCabecMsg;
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NfeStatusServicoNFResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico")]
        public VigoNFE.Status3_BA.nfeCabecMsg nfeCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico", Order=0)]
        public System.Xml.XmlNode NfeStatusServicoNFResult;
        
        public NfeStatusServicoNFResponse() {
        }
        
        public NfeStatusServicoNFResponse(VigoNFE.Status3_BA.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode NfeStatusServicoNFResult) {
            this.nfeCabecMsg = nfeCabecMsg;
            this.NfeStatusServicoNFResult = NfeStatusServicoNFResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NfeStatusServicoSoapChannel : VigoNFE.Status3_BA.NfeStatusServicoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NfeStatusServicoSoapClient : System.ServiceModel.ClientBase<VigoNFE.Status3_BA.NfeStatusServicoSoap>, VigoNFE.Status3_BA.NfeStatusServicoSoap {
        
        public NfeStatusServicoSoapClient() {
        }
        
        public NfeStatusServicoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NfeStatusServicoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfeStatusServicoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfeStatusServicoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VigoNFE.Status3_BA.NfeStatusServicoNFResponse VigoNFE.Status3_BA.NfeStatusServicoSoap.NfeStatusServicoNF(VigoNFE.Status3_BA.NfeStatusServicoNFRequest request) {
            return base.Channel.NfeStatusServicoNF(request);
        }
        
        public System.Xml.XmlNode NfeStatusServicoNF(ref VigoNFE.Status3_BA.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            VigoNFE.Status3_BA.NfeStatusServicoNFRequest inValue = new VigoNFE.Status3_BA.NfeStatusServicoNFRequest();
            inValue.nfeCabecMsg = nfeCabecMsg;
            inValue.nfeDadosMsg = nfeDadosMsg;
            VigoNFE.Status3_BA.NfeStatusServicoNFResponse retVal = ((VigoNFE.Status3_BA.NfeStatusServicoSoap)(this)).NfeStatusServicoNF(inValue);
            nfeCabecMsg = retVal.nfeCabecMsg;
            return retVal.NfeStatusServicoNFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VigoNFE.Status3_BA.NfeStatusServicoNFResponse> VigoNFE.Status3_BA.NfeStatusServicoSoap.NfeStatusServicoNFAsync(VigoNFE.Status3_BA.NfeStatusServicoNFRequest request) {
            return base.Channel.NfeStatusServicoNFAsync(request);
        }
        
        public System.Threading.Tasks.Task<VigoNFE.Status3_BA.NfeStatusServicoNFResponse> NfeStatusServicoNFAsync(VigoNFE.Status3_BA.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            VigoNFE.Status3_BA.NfeStatusServicoNFRequest inValue = new VigoNFE.Status3_BA.NfeStatusServicoNFRequest();
            inValue.nfeCabecMsg = nfeCabecMsg;
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((VigoNFE.Status3_BA.NfeStatusServicoSoap)(this)).NfeStatusServicoNFAsync(inValue);
        }
    }
}
