//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigoNFE.Envia3_BA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", ConfigurationName="Envia3_BA.NfeAutorizacaoSoap")]
    public interface NfeAutorizacaoSoap {
        
        // CODEGEN: Generating message contract since the operation NfeAutorizacaoLote is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao/NfeAutorizacaoLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VigoNFE.Envia3_BA.NfeAutorizacaoLoteResponse NfeAutorizacaoLote(VigoNFE.Envia3_BA.NfeAutorizacaoLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao/NfeAutorizacaoLote", ReplyAction="*")]
        System.Threading.Tasks.Task<VigoNFE.Envia3_BA.NfeAutorizacaoLoteResponse> NfeAutorizacaoLoteAsync(VigoNFE.Envia3_BA.NfeAutorizacaoLoteRequest request);
        
        // CODEGEN: Generating message contract since the operation NfeAutorizacaoLoteZip is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao/NfeAutorizacaoLoteZip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VigoNFE.Envia3_BA.NfeAutorizacaoLoteZipResponse NfeAutorizacaoLoteZip(VigoNFE.Envia3_BA.NfeAutorizacaoLoteZipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao/NfeAutorizacaoLoteZip", ReplyAction="*")]
        System.Threading.Tasks.Task<VigoNFE.Envia3_BA.NfeAutorizacaoLoteZipResponse> NfeAutorizacaoLoteZipAsync(VigoNFE.Envia3_BA.NfeAutorizacaoLoteZipRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao")]
    public partial class nfeCabecMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versaoDadosField;
        
        private string cUFField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string versaoDados {
            get {
                return this.versaoDadosField;
            }
            set {
                this.versaoDadosField = value;
                this.RaisePropertyChanged("versaoDados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cUF {
            get {
                return this.cUFField;
            }
            set {
                this.cUFField = value;
                this.RaisePropertyChanged("cUF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NfeAutorizacaoLoteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao")]
        public VigoNFE.Envia3_BA.nfeCabecMsg nfeCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public NfeAutorizacaoLoteRequest() {
        }
        
        public NfeAutorizacaoLoteRequest(VigoNFE.Envia3_BA.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            this.nfeCabecMsg = nfeCabecMsg;
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NfeAutorizacaoLoteResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao")]
        public VigoNFE.Envia3_BA.nfeCabecMsg nfeCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", Order=0)]
        public System.Xml.XmlNode NfeAutorizacaoLoteResult;
        
        public NfeAutorizacaoLoteResponse() {
        }
        
        public NfeAutorizacaoLoteResponse(VigoNFE.Envia3_BA.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode NfeAutorizacaoLoteResult) {
            this.nfeCabecMsg = nfeCabecMsg;
            this.NfeAutorizacaoLoteResult = NfeAutorizacaoLoteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NfeAutorizacaoLoteZipRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao")]
        public VigoNFE.Envia3_BA.nfeCabecMsg nfeCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", Order=0)]
        public string nfeDadosMsgZip;
        
        public NfeAutorizacaoLoteZipRequest() {
        }
        
        public NfeAutorizacaoLoteZipRequest(VigoNFE.Envia3_BA.nfeCabecMsg nfeCabecMsg, string nfeDadosMsgZip) {
            this.nfeCabecMsg = nfeCabecMsg;
            this.nfeDadosMsgZip = nfeDadosMsgZip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NfeAutorizacaoLoteZipResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao")]
        public VigoNFE.Envia3_BA.nfeCabecMsg nfeCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", Order=0)]
        public System.Xml.XmlNode NfeAutorizacaoLoteZipResult;
        
        public NfeAutorizacaoLoteZipResponse() {
        }
        
        public NfeAutorizacaoLoteZipResponse(VigoNFE.Envia3_BA.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode NfeAutorizacaoLoteZipResult) {
            this.nfeCabecMsg = nfeCabecMsg;
            this.NfeAutorizacaoLoteZipResult = NfeAutorizacaoLoteZipResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NfeAutorizacaoSoapChannel : VigoNFE.Envia3_BA.NfeAutorizacaoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NfeAutorizacaoSoapClient : System.ServiceModel.ClientBase<VigoNFE.Envia3_BA.NfeAutorizacaoSoap>, VigoNFE.Envia3_BA.NfeAutorizacaoSoap {
        
        public NfeAutorizacaoSoapClient() {
        }
        
        public NfeAutorizacaoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NfeAutorizacaoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfeAutorizacaoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfeAutorizacaoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VigoNFE.Envia3_BA.NfeAutorizacaoLoteResponse VigoNFE.Envia3_BA.NfeAutorizacaoSoap.NfeAutorizacaoLote(VigoNFE.Envia3_BA.NfeAutorizacaoLoteRequest request) {
            return base.Channel.NfeAutorizacaoLote(request);
        }
        
        public System.Xml.XmlNode NfeAutorizacaoLote(ref VigoNFE.Envia3_BA.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            VigoNFE.Envia3_BA.NfeAutorizacaoLoteRequest inValue = new VigoNFE.Envia3_BA.NfeAutorizacaoLoteRequest();
            inValue.nfeCabecMsg = nfeCabecMsg;
            inValue.nfeDadosMsg = nfeDadosMsg;
            VigoNFE.Envia3_BA.NfeAutorizacaoLoteResponse retVal = ((VigoNFE.Envia3_BA.NfeAutorizacaoSoap)(this)).NfeAutorizacaoLote(inValue);
            nfeCabecMsg = retVal.nfeCabecMsg;
            return retVal.NfeAutorizacaoLoteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VigoNFE.Envia3_BA.NfeAutorizacaoLoteResponse> VigoNFE.Envia3_BA.NfeAutorizacaoSoap.NfeAutorizacaoLoteAsync(VigoNFE.Envia3_BA.NfeAutorizacaoLoteRequest request) {
            return base.Channel.NfeAutorizacaoLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<VigoNFE.Envia3_BA.NfeAutorizacaoLoteResponse> NfeAutorizacaoLoteAsync(VigoNFE.Envia3_BA.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            VigoNFE.Envia3_BA.NfeAutorizacaoLoteRequest inValue = new VigoNFE.Envia3_BA.NfeAutorizacaoLoteRequest();
            inValue.nfeCabecMsg = nfeCabecMsg;
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((VigoNFE.Envia3_BA.NfeAutorizacaoSoap)(this)).NfeAutorizacaoLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VigoNFE.Envia3_BA.NfeAutorizacaoLoteZipResponse VigoNFE.Envia3_BA.NfeAutorizacaoSoap.NfeAutorizacaoLoteZip(VigoNFE.Envia3_BA.NfeAutorizacaoLoteZipRequest request) {
            return base.Channel.NfeAutorizacaoLoteZip(request);
        }
        
        public System.Xml.XmlNode NfeAutorizacaoLoteZip(ref VigoNFE.Envia3_BA.nfeCabecMsg nfeCabecMsg, string nfeDadosMsgZip) {
            VigoNFE.Envia3_BA.NfeAutorizacaoLoteZipRequest inValue = new VigoNFE.Envia3_BA.NfeAutorizacaoLoteZipRequest();
            inValue.nfeCabecMsg = nfeCabecMsg;
            inValue.nfeDadosMsgZip = nfeDadosMsgZip;
            VigoNFE.Envia3_BA.NfeAutorizacaoLoteZipResponse retVal = ((VigoNFE.Envia3_BA.NfeAutorizacaoSoap)(this)).NfeAutorizacaoLoteZip(inValue);
            nfeCabecMsg = retVal.nfeCabecMsg;
            return retVal.NfeAutorizacaoLoteZipResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VigoNFE.Envia3_BA.NfeAutorizacaoLoteZipResponse> VigoNFE.Envia3_BA.NfeAutorizacaoSoap.NfeAutorizacaoLoteZipAsync(VigoNFE.Envia3_BA.NfeAutorizacaoLoteZipRequest request) {
            return base.Channel.NfeAutorizacaoLoteZipAsync(request);
        }
        
        public System.Threading.Tasks.Task<VigoNFE.Envia3_BA.NfeAutorizacaoLoteZipResponse> NfeAutorizacaoLoteZipAsync(VigoNFE.Envia3_BA.nfeCabecMsg nfeCabecMsg, string nfeDadosMsgZip) {
            VigoNFE.Envia3_BA.NfeAutorizacaoLoteZipRequest inValue = new VigoNFE.Envia3_BA.NfeAutorizacaoLoteZipRequest();
            inValue.nfeCabecMsg = nfeCabecMsg;
            inValue.nfeDadosMsgZip = nfeDadosMsgZip;
            return ((VigoNFE.Envia3_BA.NfeAutorizacaoSoap)(this)).NfeAutorizacaoLoteZipAsync(inValue);
        }
    }
}
