//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigoNFE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico2")]
        public string VigoNFE_Status3_MT_NfeStatusServico2 {
            get {
                return ((string)(this["VigoNFE_Status3_MT_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeStatusServico3")]
        public string VigoNFE_Status3_PR_NfeStatusServico3 {
            get {
                return ((string)(this["VigoNFE_Status3_PR_NfeStatusServico3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta2")]
        public string VigoNFE_Protocolo3_MT_NfeConsulta2 {
            get {
                return ((string)(this["VigoNFE_Protocolo3_MT_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfews/v2/services/RecepcaoEvento")]
        public string VigoNFE_Evento3_MT_RecepcaoEvento {
            get {
                return ((string)(this["VigoNFE_Evento3_MT_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeAutorizacao")]
        public string VigoNFE_Envia3_MT_NfeAutorizacao {
            get {
                return ((string)(this["VigoNFE_Envia3_MT_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeRetAutorizacao")]
        public string VigoNFE_Retorno3_MT_NfeRetAutorizacao {
            get {
                return ((string)(this["VigoNFE_Retorno3_MT_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeConsulta3")]
        public string VigoNFE_Protocolo3_PR_NfeConsulta3 {
            get {
                return ((string)(this["VigoNFE_Protocolo3_PR_NfeConsulta3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe2.fazenda.pr.gov.br/nfe-evento/NFeRecepcaoEvento")]
        public string VigoNFE_Evento3_PR_RecepcaoEvento {
            get {
                return ((string)(this["VigoNFE_Evento3_PR_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeAutorizacao3")]
        public string VigoNFE_Envia3_PR_NfeAutorizacao3 {
            get {
                return ((string)(this["VigoNFE_Envia3_PR_NfeAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeRetAutorizacao3")]
        public string VigoNFE_Retorno3_PR_NfeRetAutorizacao3 {
            get {
                return ((string)(this["VigoNFE_Retorno3_PR_NfeRetAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeStatusServico2")]
        public string VigoNFE_Status2_CE_NfeStatusServico2 {
            get {
                return ((string)(this["VigoNFE_Status2_CE_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeConsulta2")]
        public string VigoNFE_Protocolo2_CE_NfeConsulta2 {
            get {
                return ((string)(this["VigoNFE_Protocolo2_CE_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br/nfe2/services/RecepcaoEvento")]
        public string VigoNFE_Evento2_CE_RecepcaoEvento {
            get {
                return ((string)(this["VigoNFE_Evento2_CE_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeRecepcao2")]
        public string VigoNFE_Envia2_CE_NfeRecepcao2 {
            get {
                return ((string)(this["VigoNFE_Envia2_CE_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeRetRecepcao2")]
        public string VigoNFE_Retorno2_CE_NfeRetRecepcao2 {
            get {
                return ((string)(this["VigoNFE_Retorno2_CE_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeStatusServico2")]
        public string VigoNFE_Status3_PE_NfeStatusServico2 {
            get {
                return ((string)(this["VigoNFE_Status3_PE_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeConsulta2")]
        public string VigoNFE_Protocolo3_PE_NfeConsulta2 {
            get {
                return ((string)(this["VigoNFE_Protocolo3_PE_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/RecepcaoEvento")]
        public string VigoNFE_Evento3_PE_RecepcaoEvento {
            get {
                return ((string)(this["VigoNFE_Evento3_PE_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeAutorizacao")]
        public string VigoNFE_Envia3_PE_NfeAutorizacao {
            get {
                return ((string)(this["VigoNFE_Envia3_PE_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeRetAutorizacao")]
        public string VigoNFE_Retorno3_PE_NfeRetAutorizacao {
            get {
                return ((string)(this["VigoNFE_Retorno3_PE_NfeRetAutorizacao"]));
            }
        }
    }
}
